#!/usr/bin/env luajit

local ffi = require("ffi")

-- NOTE: Debian includes the '.so' symlinks only with the '-dev' packages,
--  so explicitly specify the major version in order to not depend on them.
local X = ffi.load("X11.so.6")

local io = require("io")
local os = require("os")
local string = require("string")
local table = require("table")

local kb_layout_util = require("kb_layout_util")

local assert = assert
local error = error
local ipairs = ipairs
local loadfile = loadfile
local print = print
local tonumber = tonumber
local type = type

local arg = arg

----------

if (arg[1] == nil) then
    print("Usage: mkcodepoints.lua <layoutFile1> [<layoutFile2> ...]")
    print(" (Layout files generated by mklayout.lua reside in layout/)")
    os.exit(1)
end

ffi.cdef[[
typedef uint32_t KeySym;
KeySym XStringToKeysym(const char *string);
]]

local function readMnemonicMap()
    local SymDefFileName = "/usr/include/X11/keysymdef.h"
    local codePts = {}

    local SP_ = "[ \t]"
    local SPp, SPz = SP_..'+', SP_..'*'
    local CommentStartPat = "/%*[%"..string.char(40).." ]"  -- ASCII 40: paren-open

    -- NOTE: the comment in the header file permits to match textually. We slightly
    --  tweak the pattern from the Perl regex there.
    local PrefixPattern = "^"..SPz.."#"..SPz.."define XK_([a-zA-Z_0-9]+)"..SPp.."0x[0-9a-fA-F]+(.*)"
    local SuffixPattern = SPz..CommentStartPat.."U%+([0-9a-fA-F]+)"

    local lineNum = 0
    local readCodePtCount = 0

    for line in io.lines(SymDefFileName) do
        lineNum = lineNum + 1
        local mnemonic, rest = line:match(PrefixPattern)

        if (codePts[mnemonic] ~= nil) then
            error(("%s:%d: Duplicate mnemonic '%s'"):format(
                    SymDefFileName, lineNum, mnemonic))
        end

        if (mnemonic == "NoSymbol") then
            error(("%s:%d: Unexpected mnemonic '%s'"):format(
                    SymDefFileName, lineNum, mnemonic))
        end

        if (mnemonic ~= nil) then
            local codePtStr = rest:match(SuffixPattern)

            if (codePtStr == nil) then
                -- OK, mnemonic with a keysym but no UCS code point.
                codePts[mnemonic] = true
            else
                -- NOTE [CODEPT_BOUND]: on Raspbian Buster, there are always four hex digits
                --  after the 'U+', even though the regex in the comment allows up to 6.
                if (#codePtStr ~= 4) then
                    error(("%s:%d: Unexpected length of code point string %d"):format(
                            SymDefFileName, lineNum, #codePtStr))
                end

                local codePt = tonumber("0x"..codePtStr)
                assert(codePt ~= nil)

                codePts[mnemonic] = codePt
                readCodePtCount = readCodePtCount + 1
            end
        end
    end

    if (readCodePtCount == 0) then
        error("Did not read any code points from "..SymDefFileName)
    end

    codePts["NoSymbol"] = codePts["VoidSymbol"]

    return codePts
end

-- [<mnemonic>] = true | <UCS code point>
local allCodePts = readMnemonicMap()

----------

-- KEEPINSYNC moonglow/build.lua's MAX.TILES
local MAXTILES = 30720

local TotalDestKeyCount = 40
local KeyIdxFactor = 10
local MaxShift = 2

local mnemonics = {}  -- [<running index>] = mnemonic
local codePts = {}  -- sub-map of 'allCodePts'

local function isMnemonicUCS(mnemonic)
    -- Notes:
    --  * Match exactly four hex digits for now, potentially prefixed by a single a zero.
    --  * For more disjointness it should be only uppercase letters, but lowercase do appear
    --    as well. (Though less frequently.)
    return mnemonic:match("^U0?[0-9A-Fa-f][0-9A-Fa-f][0-9A-Fa-f][0-9A-Fa-f]$")
end

local function isSpecialMnemonic(mnemonic)
    return
        -- NOTE: do not exclude digit characters!
        -- FIXME: what was this about?
        mnemonic:match("^[0-9][0-9]+$") or
        mnemonic:match("^0x[0-9A-Fa-f]+$")
end

local FixedFunctionMnemonics = {
    "BackSpace", "Tab", "Return", "Escape", "Delete",
    "space"
}

local IsFixedFunctionMnemonic = {}
do
    for _, m in ipairs(FixedFunctionMnemonics) do
        IsFixedFunctionMnemonic[m] = true
    end
end

for _, layoutFileName in ipairs(arg) do
    local layoutTab, msg = kb_layout_util.get_table(loadfile(layoutFileName))
    if (layoutTab == nil) then
        io.stderr:write(("ERROR: failed loading '%s' as Lua table: %s\n")
                :format(layoutFileName, msg))
        os.exit(2)
    end

    for k = 1, TotalDestKeyCount do
        for s = 0, MaxShift do
            local ourKeyIdx = KeyIdxFactor*k + s
            local mnemonic = layoutTab[ourKeyIdx]

            if (IsFixedFunctionMnemonic[mnemonic]) then
                error(("%s: mnemonic '%s' is reserved for fixed functionality")
                        :format(layoutFileName, mnemonic))
            end

            if (mnemonic ~= nil and not isSpecialMnemonic(mnemonic)) then
                if (codePts[mnemonic] == nil) then
                    -- NOTE: it's redundant to enter the mapping for 'U<hexdigit>*'
                    --  mnemonics into the table for the mapping aspect, but since it will
                    --  also be used for validation of input from the server, go ahead.
                    local directCodePt = isMnemonicUCS(mnemonic) and tonumber("0x"..mnemonic:sub(2)) or nil
                    local mappedCodePt = allCodePts[mnemonic]
                    local codePt = directCodePt or mappedCodePt
                    if (codePt == nil) then
                        error(("%s: failed obtaining UCS codepoint for mnemonic '%s'")
                                :format(layoutFileName, mnemonic))
                    elseif (directCodePt and mappedCodePt) then
                        error(("%s: mnemonic '%s' is ambiguous")
                                :format(layoutFileName, mnemonic))
                    end

                    -- Due to CODEPT_BOUND:
                    assert(type(codePt) ~= "number" or (codePt >= 0 and codePt <= 0xffff))

                    if (type(codePt) == "number" and not (codePt >= 0 and codePt < MAXTILES)) then
                        io.stderr:write(("%s: warning: dropping mnemonic '%s' with codepoint %d\n")
                                :format(layoutFileName, mnemonic, codePt))
                    else
                        mnemonics[#mnemonics + 1] = mnemonic
                        codePts[mnemonic] = codePt
                    end
                end
            end
        end
    end
end

-- Fixed-functionality mnemonics.
for _, mnemonic in ipairs(FixedFunctionMnemonics) do
    mnemonics[#mnemonics + 1] = mnemonic
    codePts[mnemonic] = 0
end

table.sort(mnemonics)

local strTab = {
    "#!/bin/false ljremarkable UCS code points (low 16 bits) + X KeySym values (high bits)",
    "-- -*-lua-*-",
    "return {"
}

for _, mnemonic in ipairs(mnemonics) do
    local codePt = codePts[mnemonic]
    assert(codePt)

    local isNumber = (type(codePt) == "number")
    assert(isNumber or codePt == true)
    local keySym = isNumber and X.XStringToKeysym(mnemonic) or nil

    if (keySym == 0) then
        error(("No KeySym for mnemonic '%s'"):format(mnemonic))
    end

    strTab[#strTab + 1] = ("[%q]=%s,%s"):format(
        mnemonic, (keySym ~= nil) and ("0x%x"):format(0x10000*keySym + codePt) or codePt,
        codePt == 0 and "  -- fixed-function" or "")
end

strTab[#strTab + 1] = "}\n"

io.stdout:write(table.concat(strTab, '\n'))
