
USER root
# Make sure that /usr/include/linux/fb.h is present:
RUN @install@ $pkg_linux_headers

USER user
WORKDIR /home/user

## Build LuaJIT for the reMarkable tablet.
#@if-ljrM: RUN git clone luajit-2.1 ./luajit-2.1-rM
#@if-ljrM: RUN (cd luajit-2.1 && commit=`git rev-parse --verify HEAD` && cd ../luajit-2.1-rM && git checkout $commit)

#@if-ljrM: WORKDIR /home/user/luajit-2.1-rM
# NOTE: the reMarkable toolchain also has '-march=armv7-a' but that seems redundant
#  because it's implied by Cortex-A9.
#@if-ljrM: RUN sed -i 's/^CCOPT_arm=$/CCOPT_arm= -mfpu=neon -mfloat-abi=hard -mcpu=cortex-a9/' ./src/Makefile
#@if-ljrM: RUN make -j4
#@if-ljrM: RUN sha256sum src/luajit | grep -q daf5b359a0b1c102a36f77d6cfe941105b3cea1693fa1b3ee15c341d886525c6
#@if-ljrM: WORKDIR /home/user

########## Check out and build ljremarkable ##########

COPY ./additional.git/ ./ljremarkable.git/

# Create a non-bare repository:
RUN git clone ./ljremarkable.git ./ljremarkable

WORKDIR ljremarkable

RUN sed -i 's|https://github.com/helixhorned/ljclang|../ljclang|g' .gitmodules
RUN git submodule init
RUN git submodule update ljclang

# Avoid checking out the whole libremarkable repository. We only need one header.
RUN mkdir -p libremarkable/legacy-c-impl/libremarkable
WORKDIR libremarkable/legacy-c-impl/libremarkable
RUN wget https://raw.githubusercontent.com/canselcik/libremarkable/master/legacy-c-impl/libremarkable/lib.h
RUN sha256sum lib.h | grep -q 2e718a10e9c47e4cde5387e834b1a0d76964378cf6247e8e045bf92f6d1a6db4

# Install conditional run-time library dependencies (libX11.so.6 and libXtst.so.6).
# For the resulting '.app.lua', we want 'xlib.lua' to be included unconditionally,
# therefore the 'require()' for it must succeed.
USER root
RUN @install@ $pkg_libxtst
USER user

# Build the application.
WORKDIR ../../..
RUN cp -a /home/user/ljclang/Makefile ljclang/
RUN DISPLAY=dummy make app
